name: test

on: [push, pull_request]

jobs:
  sphinx:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
        rails: [ '5_0', '5_1', '5_2', '6_0', '6_1', '7_0', '7_1' ]
        database: [ 'mysql2', 'postgresql' ]
        sphinx_version: [ '2.2.11', '3.4.1' ]
        sphinx_engine: [ 'sphinx' ]
        exclude:
          - database: 'postgresql'
            sphinx_version: '3.4.1'
            sphinx_engine: 'sphinx'
          - ruby: '3.0'
            rails: '5_0'
          - ruby: '3.0'
            rails: '5_1'
          - ruby: '3.0'
            rails: '5_2'
          - ruby: '3.1'
            rails: '5_0'
          - ruby: '3.1'
            rails: '5_1'
          - ruby: '3.1'
            rails: '5_2'
          - ruby: '3.2'
            rails: '5_0'
          - ruby: '3.2'
            rails: '5_1'
          - ruby: '3.2'
            rails: '5_2'

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thinking_sphinx
          POSTGRES_DB: thinking_sphinx
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: thinking_sphinx
          MYSQL_DATABASE: thinking_sphinx
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          ruby-version: ${{ matrix.ruby }}
          rails-version: ${{ matrix.rails }}
          sphinx-version: ${{ matrix.sphinx_version }}
          sphinx-engine: ${{ matrix.sphinx_engine }}
          database: ${{ matrix.database }}
        timeout-minutes: 12

  manticore:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
        rails: [ '5_0', '5_1', '5_2', '6_0', '6_1', '7_0', '7_1' ]
        database: [ 'mysql2', 'postgresql' ]
        sphinx_version: [ '4.0.2', '6.0.0' ]
        sphinx_engine: [ 'manticore' ]
        exclude:
          - ruby: '3.0'
            rails: '5_0'
          - ruby: '3.0'
            rails: '5_1'
          - ruby: '3.0'
            rails: '5_2'
          - ruby: '3.1'
            rails: '5_0'
          - ruby: '3.1'
            rails: '5_1'
          - ruby: '3.1'
            rails: '5_2'
          - ruby: '3.2'
            rails: '5_0'
          - ruby: '3.2'
            rails: '5_1'
          - ruby: '3.2'
            rails: '5_2'

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thinking_sphinx
          POSTGRES_DB: thinking_sphinx
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: thinking_sphinx
          MYSQL_DATABASE: thinking_sphinx
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          ruby-version: ${{ matrix.ruby }}
          rails-version: ${{ matrix.rails }}
          sphinx-version: ${{ matrix.sphinx_version }}
          sphinx-engine: ${{ matrix.sphinx_engine }}
          database: ${{ matrix.database }}
        timeout-minutes: 12
